[versions]
kotlin = "1.9.0"

xemanticOsc = "2.0-SNAPSHOT"

kotlinLogging = "3.0.5"
slf4j = "2.0.7"
log4j = "2.20.0"
jackson = "2.15.2"

gradleVersionsPlugin = "0.47.0"

[libraries]
xemantic-osc-udp = { module = "com.xemantic.osc:xemantic-osc-udp", version.ref = "xemanticOsc" }

kotlin-logging = { module = "io.github.microutils:kotlin-logging", version.ref = "kotlinLogging" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
log4j-slf4j2 = { group = "org.apache.logging.log4j", name = "log4j-slf4j2-impl", version.ref = "log4j" }
log4j-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
jackson-json = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-yaml", version.ref = "jackson" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
gradle-versions-plugin = { id = "com.github.ben-manes.versions", version.ref = "gradleVersionsPlugin" }
